### ISSUE TITLE
Discord Rich Presence Integration

### ISSUE THREAD

**Issue by CrushyGreenRen** [jakubg1/OpenSMCE#14]
Maybe there could be a json file (with some code in the program that makes it work) that determines/grabs:

- If the RPC is enabled.
- What ID should the mod has.
- Difficulty (once it gets implemented)
- What levels/menus/etc use for the image assets.
- If there is no json file then the RPC is off.

**Comment by jakubg1** [comment]
This seems like a cool idea, however I'm not sure if it is possible with capabilities of Lua and LOVE2D. A mod "marketplace" where you can browse games and download these you like is definitely a cool idea.

**Comment by jakubg1** [comment]
Note that the above comment was a misinterpretation. Relates to #15

**Comment by jakubg1** [comment]
Closed as #15 was closed too. I don't see any point of the issue being open.
