### ISSUE TITLE
Sphere selectors

### ISSUE THREAD

**Issue by jakubg1** [jakubg1/OpenSMCE#39]
Allow to create, based on some criteria such as position or color, an instance of a class that would contain a list of spheres with which you can do varius stuff, such as change their color or destroy them.
This would be useful for most powerups which mess with spheres. Currently, all that stuff is in Session.lua which isn't the best place to store all these functions.

**Comment by TF3RDL** [comment]
This can hopefully improve flexibility on powerups that affect spheres in any way (like color replacer should affect two colors and leave wild spheres intact when they hit a wild ball per #65)

**Comment by jakubg1** [comment]
That's good you mentioned color replacers, they may be a bit of a problem because there would need to be various parameters for sphere selectors which exist in one context but not in the other, such as color. That remains to be seen, though.

**Comment by jakubg1** [comment]
Under the hood, sphere destruction should support #121.
Example sphere selectors:

`sphere_selectors/color_bomb_1.spsel`:
```json
{
    "conditions": [
        {
            "type": "color",
            "colors": [1]
        },
        {
            "type": "isOffscreen",
            "value": false
        }
    ]
}
```
or alternatively:
```json
{
    "condition": "$expr{[color] == 1 && ![isOffscreen]}"
}
```

`sphere_selectors/fireball.spsel`:
```json
{
    "conditions": [
        {
            "type": "distance",
            "max": 75
        }
    ]
}
```
or alternatively:
```json
{
    "condition": "$expr{[distance] < 75}"
}
```

`sphere_selectors/lightning.spsel`:
```json
{
    "conditions": [
        {
            "type": "distanceX",
            "max": 50
        }
    ]
}
```
or alternatively:
```json
{
    "condition": "$expr{[distanceX] < 50}"
}
```

`sphere_selectors/everything.spsel`:
```json
{
    "conditions": []
}
```
or alternatively:
```json
{
    "condition": "$expr{true}"
}
```

**Comment by jakubg1** [comment]
Another approach:
`sphere_selectors/color_bomb_1.json`:
```json
{
  "operations": [
    {"type": "add", "condition": "$expr{[sphere.color] == 1 && ![sphere.isOffscreen]}"}
  ]
}
```

`sphere_selectors/fireball.json`:
```json
{
  "operations": [
    {"type": "add", "condition": "$expr{[sphere.distance] < 100}"}
  ]
}
```

`sphere_selectors/lightning.json`:
```json
{
  "operations": [
    {"type": "add", "condition": "$expr{[sphere.distanceX] < 50}"}
  ]
}
```

`sphere_selectors/everything.json`:
```json
{
  "operations": [
    {"type": "add", "condition": true}
  ]
}
```

And hypothetical `sphere_selectors/limited_color_bomb_2.json`:
```json
{
  "operations": [
    {"type": "add", "condition": "$expr{[sphere.color] == 2 && ![sphere.isOffscreen]}"},
    {"type": "pickRandomly", "count": 20}
  ]
}
```

**Comment by jakubg1** [comment]
Implemented: https://github.com/jakubg1/OpenSMCE/commit/fd508a2c429b10f3fd8e0f67288e35b1d9611021
