### ISSUE TITLE
Importing is sometimes finicky

### ISSUE THREAD

**Issue by CrushyGreenRen** [jakubg1/OpenSMCE#6]
I don't exactly know how to replicate this bug, but I had a _somewhat_ incomplete data folder so I re-extracted Luxor 1's mjz files. (later on I realized that QuickBMS somehow did not extract the main files, which is a non-OpenSMCE problem).
They turned out mostly the same, but re-doing the conversion process caused the program to not extract all the files.
img: https://cdn.discordapp.com/attachments/455322611178668032/735763257935003690/unknown.png

**Comment by jakubg1** [comment]
Since then the converter has had undergone big changes, however I'm keeping this ticket open and hearing out for any future problems.

One known issue is that the converter is partially useless on MacOS and Linux-based operating systems.

**Comment by jakubg1** [comment]
I will close the ticket as the converter has got its own repository. Any precise limitations, problems or ideas should be submitted on its own issue list.
