### ISSUE TITLE
Speed Shot Beam Suggestions

### ISSUE THREAD

**Issue by CrushyGreenRen** [jakubg1/OpenSMCE#9]
Seeing the Speed Shot beam gives me these ideas:
Option 1 is to have it always be extended 
Option 2 is to have it abruptly cut (like in vanilla 1/AR).
Option 3 is to have it be squished depending on how close the nearest sphere is (Zuma/Luxor 2).

**Comment by jakubg1** [comment]
Implemented in https://github.com/jakubg1/OpenSMCE/commit/1ba09621783ba2b41e5d6df92941fd249efcb0a7
