### ISSUE TITLE
Custom game resolutions scale back to 800x600 on resize

### ISSUE THREAD

**Issue by ShamblesSM** [jakubg1/OpenSMCE#96]
The game window will look fine if it's not resized in any way:
![image](https://user-images.githubusercontent.com/115082072/218827828-3ee5de42-023c-4041-b386-0c8967bcff80.png)

Resizing it however, will scale it to 800x600 and won't be restored until the game is restarted.
![image](https://user-images.githubusercontent.com/115082072/218827926-b4c66960-78ff-46de-bbbf-93600dcb3afb.png)

Toggling Fullscreen on and off will entirely set the window to 800x600.

**Comment by jakubg1** [comment]
Fixed: https://github.com/jakubg1/OpenSMCE/commit/f375b20a9de0ab0bf0350856e71d9fb8d0670ce0
